site_name: EthHub
site_description: Essential source for Ethereum information.
theme:
  name: 'material'
  custom_dir: 'docs/material'
  palette:
    primary: 'ethhub'
  logo: 'logo.png'
  favicon: 'assets/images/favicon.ico'
  feature:
    tabs: true

extra_css: [extra.css]
markdown_extensions:
  - meta

repo_name: 'ethhub-io/ethhub-zh'
repo_url: 'https://github.com/ethhub-io/ethhub-zh'

extra:
  social:
    - type: 'github'
      link: 'https://github.com/ethhub-io/ethhub'
    - type: 'twitter'
      link: 'https://twitter.com/ethhub_io'
    - type: 'medium'
      link: 'https://medium.com/ethhub'
    - type: 'comment'
      link: 'https://discordapp.com/invite/gw8AM98'
    - type: 'instagram'
      link: 'https://www.instagram.com/ethhub_io/'

google_analytics:
  - 'UA-125892125-2'
  - 'auto'

nav:
- 首页: 'index.md'
- 文档: 'ethereum-basics/以太坊是什么.md'
- 播客: 'https://podcast.ethhub.io'
- 新闻: 'https://ethhub.substack.com/'
- 商城: 'https://shop.ethhub.io'
- 以太坊基础:
  - '以太坊是什么？': 'ethereum-basics/以太坊是什么.md'
  - '以太坊货币政策': 'ethereum-basics/以太坊货币政策.md'
- 以太坊路线图:
  - 以太坊 2.0:
      - '以太坊2.0各阶段': 'ethereum-roadmap/ethereum-2.0/以太坊2.0各阶段.md'
      - '以太坊权益证明': 'ethereum-roadmap/ethereum-2.0/以太坊权益证明.md'
      - '以太坊中的分片': 'ethereum-roadmap/ethereum-2.0/以太坊中的分片.md'
      - '以太坊2.0经济学': 'ethereum-roadmap/ethereum-2.0/以太坊2.0经济学.md'
      - '从以太坊1.0迁移到以太坊2.0': 'ethereum-roadmap/ethereum-2.0/从以太坊1.0迁移到以太坊2.0.md'
  - '以太坊1.x': 'ethereum-roadmap/以太坊1.x.md'
  - Layer 2 扩容方案:
      - 'ZK-Rollups': 'ethereum-roadmap/layer-2-scaling/zk-rollups.md'
      - 'Optimistic Rollups': 'ethereum-roadmap/layer-2-scaling/optimistic_rollups.md'
- 使用以太坊:
  - '如何购买ETH': 'using-ethereum/如何购买ETH.md'
  - '运行以太坊节点': 'using-ethereum/运行以太坊节点.md'
  - 钱包:
    - '介绍以太坊钱包': 'using-ethereum/wallets/介绍以太坊钱包.md'
    - '以太坊智能合约钱包': 'using-ethereum/wallets/以太坊智能合约钱包.md'
    - '以太坊硬件钱包': 'using-ethereum/wallets/以太坊硬件钱包.md'
    - '以太坊移动钱包': 'using-ethereum/wallets/以太坊移动钱包.md'
    - '以太坊桌面钱包': 'using-ethereum/wallets/以太坊桌面钱包.md'
    - '以太坊网页钱包': 'using-ethereum/wallets/web.md'
